git hub actions : 1

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -59,7 +59,7 @@ jobs:
     steps:
       - name: Update GitOps Repository
         run: |
-        
+
           echo "Cleaning old GitOps repository..."
           rm -rf gitops
 
@@ -91,3 +91,118 @@ jobs:
 
           echo "Pushing changes..."
           git push origin main
+
+  deploy-ec2:
+    runs-on: ubuntu-latest
+    needs: update-gitops-repo
+
+    env:
+      IMAGE_TAG: ${{ github.run_number }}
+      DOCKER_IMAGE: suryabhaskarvempala/ultimate-cicd:${{ github.run_number }}
+
+    steps:
+      - name: Deploy to EC2
+        uses: appleboy/ssh-action@v1.2.2
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            echo "Connected to EC2"
+
+            echo "Checking Docker..."
+
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+
+              sudo apt-get update
+              sudo apt-get install -y docker.io
+
+              sudo systemctl enable docker
+              sudo systemctl start docker
+            else
+              echo "Docker already installed"
+            fi
+
+            echo "Docker version:"
+            docker --version
+
+            echo "Pulling image:"
+            echo "${DOCKER_IMAGE}"
+
+            sudo docker pull ${DOCKER_IMAGE}
+
+            echo "Stopping old container..."
+
+            sudo docker stop node-app || true
+
+            echo "Removing old container..."
+
+            sudo docker rm node-app || true
+
+            echo "Starting new container..."
+
+            sudo docker run -d \
+              --name node-app \
+              -p 8080:8080 \
+              ${DOCKER_IMAGE}
+
+            echo "Deployment completed"
+
+            echo "Running containers:"
+
+            sudo docker ps
+
+  notify:
+    runs-on: ubuntu-latest
+
+    needs:
+      - build
+      - deploy-image
+      - update-gitops-repo
+      - deploy-ec2
+
+    if: ${{ always() && contains(needs.*.result, 'failure') }}
+
+    steps:
+      - name: Send failure email
+        uses: dawidd6/action-send-mail@v6
+        with:
+          server_address: smtp.gmail.com
+          server_port: 465
+          username: ${{ secrets.MAIL_USERNAME }}
+          password: ${{ secrets.MAIL_PASSWORD }}
+
+          subject: "🚨 CI/CD Pipeline Failed - Ultimate CICD"
+
+          to: suryabhaskarvempala@gmail.com
+          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
+
+          body: |
+            Hello Surya,
+
+            The GitHub Actions CI/CD pipeline has FAILED.
+
+            Repository:
+            ${{ github.repository }}
+
+            Branch:
+            ${{ github.ref_name }}
+
+            Commit:
+            ${{ github.sha }}
+
+            Workflow:
+            ${{ github.workflow }}
+
+            Run Number:
+            ${{ github.run_number }}
+
+            Please open the GitHub Actions workflow run and check which stage failed.
+
+            GitHub Actions:
+            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+
+            Regards,
+            GitHub Actions CI/CD
